# Generated by Django 6.0.4 on 2026-04-21 01:23

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='PerifericosNuevos',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tipo', models.CharField(max_length=50)),
                ('modelo', models.CharField(max_length=100)),
                ('antiguedad', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='PerifericosUsados',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tipo', models.CharField(max_length=50)),
                ('modelo', models.CharField(max_length=100)),
                ('antiguedad', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='SeBusca',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tipo', models.CharField(max_length=50)),
                ('modelo', models.CharField(max_length=100)),
                ('antiguedad', models.CharField(max_length=50)),
            ],
        ),
    ]
