# Generated by Django 6.0.4 on 2026-04-21 01:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='perifericosnuevos',
            name='antiguedad',
        ),
    ]
